### ISSUE TITLE
Problems with model build

### ISSUE THREAD

**Issue by suwangcn** [PolarBean/DeepSlice#10]
![image](https://user-images.githubusercontent.com/65085711/168519671-ea5ef086-6cde-4be1-8709-b2f8fce0e3ea.png)

**Comment by PolarBean** [comment]
Thanks for using DeepSlice, I can't see the full error message from your screenshot so if there is more could you please send it. Are you using the anaconda environment file included with the repo?

**Comment by PolarBean** [comment]
Ah i see google colab has made some changes to their environment. i just pushed an update to fix this :) try again now, thank you for finding this!
https://github.com/PolarBean/DeepSlice/pull/11

**Comment by suwangcn** [comment]
![image](https://user-images.githubusercontent.com/65085711/168619781-9214dcbc-d95e-4b77-881c-789a550f3fcc.png)
Yes. Thank you so much! The h5py installation you added works fine, but some other error in the code jumped out.

**Comment by PolarBean** [comment]
i just tested it and it ran on colab. 

2 things that can help
- make sure you've run the tensorflow 1.0 cell
- disconnect and delete the runtime before trying again.

**Comment by suwangcn** [comment]
It works after I reconnected it. Thank you very much!
