### ISSUE TITLE
"conda env create -f DS-CPU.yml" leads to "Solving environment: failed"  & "ResolvePackageNotFound:"

### ISSUE THREAD

**Issue by VovaNAK** [PolarBean/DeepSlice#13]
Hi Master of DeepSlicing, 

I followed the installation you mentioned and I am facing the following failure :

(envDS) Path\DeepSlice\conda_environments>conda env create -f DS-CPU.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - lz4-c==1.9.3=h295c915_1
  - mkl_random==1.2.2=py37h51133e4_0
  - sniffio==1.2.0=py37h06a4308_1
  - git==2.34.1=pl5262hc120c5b_0
  - grpcio==1.42.0=py37hce63b2e_0
  - openssl==1.1.1o=h7f8727e_0
  - blinker==1.4=py37h06a4308_0
  - libxml2==2.9.12=h03d6c58_0
  - tornado==6.1=py37h27cfd23_0
  - pip==21.2.2=py37h06a4308_0
  - libzopfli==1.0.3=he6710b0_0
  - yaml==0.2.5=h7b6447c_0
  - libgomp==9.3.0=h5101ec6_17
  - wrapt==1.13.3=py37h7f8727e_2
  - cffi==1.15.0=py37hd667e15_1
  - libcurl==7.80.0=h0b77cf5_0
  - astor==0.8.1=py37h06a4308_0
  - freetype==2.11.0=h70c0345_0
  - imagecodecs==2021.8.26=py37h4cda21f_0
  - hdf5==1.10.6=hb1b8bf9_0
  - libffi==3.3=he6710b0_2
  - icu==58.2=he6710b0_3
  - lxml==4.8.0=py37h1f438cf_0
  - nbconvert==6.3.0=py37h06a4308_0
  - snappy==1.1.8=he6710b0_0
  - mkl-service==2.4.0=py37h7f8727e_0
  - matplotlib-base==3.5.1=py37ha18d171_0
  - bzip2==1.0.8=h7b6447c_0
  - tensorflow-base==2.2.0=mkl_py37hd506778_0
  - cytoolz==0.11.0=py37h7b6447c_0
  - importlib-metadata==4.8.2=py37h06a4308_0
  - _openmp_mutex==4.5=1_gnu
  - lcms2==2.12=h3be6417_0
  - libedit==3.1.20210910=h7f8727e_0
  - libdeflate==1.8=h7f8727e_5
  - zeromq==4.3.4=h2531618_0
  - bottleneck==1.3.4=py37hce1f21e_0
  - jupyter_core==4.9.1=py37h06a4308_0
  - pyyaml==6.0=py37h7f8727e_1
  - libstdcxx-ng==9.3.0=hd4cf53a_17
  - readline==8.1.2=h7f8727e_1
  - pyrsistent==0.18.0=py37heee7806_0
  - brunsli==0.1=h2531618_0
  - charls==2.2.0=h2531618_0
  - libssh2==1.9.0=h1ba5d50_1
  - ld_impl_linux-64==2.35.1=h7274673_9
  - libgcc-ng==9.3.0=h5101ec6_17
  - websocket-client==0.58.0=py37h06a4308_4
  - cryptography==36.0.0=py37h9ce1e76_0
  - argon2-cffi-bindings==21.2.0=py37h7f8727e_0
  - debugpy==1.5.1=py37h295c915_0
  - markupsafe==2.0.1=py37h27cfd23_0
  - curl==7.80.0=h7f8727e_0
  - kiwisolver==1.3.2=py37h295c915_0
  - scipy==1.7.3=py37hc147768_0
  - sqlite==3.37.2=hc218d9a_0
  - brotlipy==0.7.0=py37h27cfd23_1003
  - xz==5.2.5=h7b6447c_0
  - libtiff==4.1.0=h2733197_1
  - pywavelets==1.1.1=py37h7b6447c_2
  - libev==4.33=h7f8727e_1
  - libsodium==1.0.18=h7b6447c_0
  - giflib==5.2.1=h7b6447c_0
  - openjpeg==2.4.0=h3ad879b_0
  - notebook==6.4.8=py37h06a4308_0
  - gettext==0.21.0=hf68c758_0
  - perl==5.26.2=h14c3975_0
  - blosc==1.21.0=h8c45485_0
  - cfitsio==3.470=hf0d0db6_6
  - mkl_fft==1.3.1=py37hd3c417c_0
  - pcre2==10.37=he7ceb23_1
  - libprotobuf==3.19.1=h4ff587b_0
  - c-ares==1.18.1=h7f8727e_0
  - zstd==1.4.9=haebb681_0
  - aiohttp==3.8.1=py37h7f8727e_0
  - libwebp==1.2.0=h89dd481_0
  - zfp==0.5.5=h295c915_6
  - libnghttp2==1.46.0=hce63b2e_0
  - ipykernel==6.4.1=py37h06a4308_1
  - frozenlist==1.2.0=py37h7f8727e_0
  - libgfortran4==7.5.0=ha8ba4b0_17
  - libaec==1.0.4=he6710b0_1
  - mistune==0.8.4=py37h14c3975_1001
  - locket==0.2.1=py37h06a4308_1
  - pyzmq==22.3.0=py37h295c915_2
  - ncurses==6.3=h7f8727e_2
  - h5py==2.10.0=py37hd6299e0_1
  - tk==8.6.11=h1ccaba5_0
  - ca-certificates==2022.4.26=h06a4308_0
  - tensorflow==2.2.0=mkl_py37h6e9ce2d_0
  - anyio==3.5.0=py37h06a4308_0
  - termcolor==1.1.0=py37h06a4308_1
  - protobuf==3.19.1=py37h295c915_0
  - mkl==2021.4.0=h06a4308_640
  - python==3.7.11=h12debd9_0
  - scikit-learn==0.23.2=py37h0573a6f_0
  - zlib==1.2.11=h7f8727e_4
  - ipython==7.31.1=py37h06a4308_0
  - jpeg==9d=h7f8727e_0
  - libxslt==1.1.34=hc22bd24_0
  - numexpr==2.8.1=py37h6abb31d_0
  - expat==2.4.4=h295c915_0
  - pillow==8.4.0=py37h5aabda8_0
  - libgfortran-ng==7.5.0=ha8ba4b0_17
  - setuptools==58.0.4=py37h06a4308_0
  - scikit-image==0.17.2=py37hdf5156a_0
  - intel-openmp==2021.4.0=h06a4308_3561
  - lerc==3.0=h295c915_0
  - markdown==3.3.4=py37h06a4308_0
  - certifi==2022.5.18.1=py37h06a4308_0
  - terminado==0.13.1=py37h06a4308_0
  - multidict==5.2.0=py37h7f8727e_2
  - libpng==1.6.37=hbc83047_0
  - jxrlib==1.1=h7b6447c_2
  - krb5==1.19.2=hac12032_0
  - brotli==1.0.9=he6710b0_2
  - yarl==1.6.3=py37h27cfd23_0

Do you have any tips ?
Cheers, 

VK

**Comment by PolarBean** [comment]
Happy to help! What operating system you are using?

**Comment by PolarBean** [comment]
it's likely related to this issue
https://stackoverflow.com/questions/49154899/resolvepackagenotfound-create-env-using-conda-and-yml-file-on-macos
If you look in the environment yml provided in this repo, you'll find that a number of requirements are under   - pip:
https://github.com/PolarBean/DeepSlice/blob/master/conda_environments/DS-CPU.yml
what you need to do is copy and paste each of these packages listed in your comment into the pip list.
please report back when you're done :)

**Comment by PolarBean** [comment]
happy slicing ⚔
