### ISSUE TITLE
save the results

### ISSUE THREAD

**Issue by gaofan83** [PolarBean/DeepSlice#19]
@PolarBean Thank you for developing deepslice tool for brain image registration.

I managed to install the tool on Ubuntu 20.04. However when I tested the following script, I got error. Can you help?

```
from DeepSlice import DeepSlice 
Model = DeepSlice()
Model.Build()
Model.predict("/home/fgao/deepslice_registration/")
```
PIL.Image.DecompressionBombError: Image size (700105140 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

I used the following script to fix the above problem.
```
from PIL import Image
Image.MAX_IMAGE_PIXELS = None
Model.predict("/home/fgao/deepslice_registration/")
Model.Save_Results("deepslice_models")
```
Then, the following error came out:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fgao/software/DeepSlice/DeepSlice.py", line 490, in Save_Results
    width, height = get_image_size(self.image_dir + os.path.sep + file)
  File "/home/fgao/software/DeepSlice/DeepSlice.py", line 61, in get_image_size
    raise Exception(f"Invalid filetype: {head}")
Exception: Invalid filetype: b'II*\x00\x08\x00\x00\x00\x0e\x00\x00\x01\x04\x00\x01\x00\x00\x00[g\x00\x00\x01\x01'

**Comment by gaofan83** [comment]
Looks like image format issue for tif. png is fine.

**Comment by PolarBean** [comment]
Hi @gaofan83, i think it may work with smaller tif files but there may be a file size limit. It is best to use downsampled PNGs as these are easiest to open in QuickNII, Visualign, and the whole QUINT workflow :) 
How are your results looking using deepslice?

**Comment by gaofan83** [comment]
Thanks @PolarBean 
As a beginner in this field, I am not sure how to work on the downstream to generate the sections.

**Comment by PolarBean** [comment]
No need to keep closing the issue :) we can do that when we've finished trouble shooting. After you have processed your DAPI file you can view the results in QuickNII (https://ebrains.eu/service/quicknii-and-visualign/) adjust the deepslice predictions here.
Then you can use Visualign (available at the link above to open the QuickNII json file and add non-linear deformations. 
Both Visualign and QuickNII can export atlas sections. If you have segmentations (such as those created in Ilastik) these can be mapped into ABA space with Nutil (https://www.nitrc.org/projects/nutil/). 

see this paper for a more detailed guide (https://www.frontiersin.org/articles/10.3389/fninf.2019.00075/full). May I ask what are you trying to quantify or visualise?
