### ISSUE TITLE
Cannot open the web DeepSlice

### ISSUE THREAD

**Issue by Virginia9733** [PolarBean/DeepSlice#20]
Am I the only person who recently cannot open the web DeepSlice?

It said:
"Something went wrong :-(
Something went wrong while trying to load this website; please try again later.

If it is your site, you should check your logs to determine what the problem is."

**Comment by PolarBean** [comment]
Yes! I just realised. I'll fix this and reboot the server when I get to work tomorrow :)

**Comment by Virginia9733** [comment]
Hi there, I am still having trouble to use the Web DeepSlice.

It said:
"Something went wrong :-(
Something went wrong while trying to load this website; please try again later.

If it is your site, you should check your logs to determine what the problem is."

**Comment by nataliekoh** [comment]
I am also having trouble accessing the site!

**Comment by PolarBean** [comment]
Yes! Sorry it will be back up soon.

**Comment by PolarBean** [comment]
It's back up :)

**Comment by nataliekoh** [comment]
Hooray! Thank you!!
