### ISSUE TITLE
Get allen corresponding slice

### ISSUE THREAD

**Issue by JulesScholler** [PolarBean/DeepSlice#21]
Hello!

I started using DeepSlice to automatically find the slice plane. I can visualize the result in QuickNII and it seems to be working fine. 

What I would like to do next is convert the anchor vectors to slice the 3D brain dataset from ABA and apply non-rigid deformation to improve the matching and then perform mapping. I have thousands of slices with only a few per animal and I need to do co-localisation so I can not really do something manual here. I tried to look for converting the anchor vectors with no luck.

Thanks and keep up the good work with this fantastic tool!

**Comment by PolarBean** [comment]
Hi! Thanks for using DeepSlice :) I'm not sure if I fully understand the issue so feel free to clarify if I misunderstand something. If you would like to generate cross sections through the atlas then QuickNII has the ability to do this. It is the Export Slices option next to save JSON. We do have a non-linear registration tool called VisuAlign however it is manual, though I'm working on some automatic methods for the future. Your options then are to either use the output of visualign with ImageJ and do the automated registration their or else you could try ABBA https://github.com/BIOP/ijp-imagetoatlas which is a fantastic registration tool, compatible with DeepSlice alongside providing automated non-linear methods.

let me know if there's something i've misunderstood :)

**Comment by JulesScholler** [comment]
I just found the definition of the anchoring vector in QuickNII paper. I will try and use it to adapt to my use case.

To be more specific my use case is to not use QuickNII and to fetch the corresponding 2D slice in the ABA automatically from DeepSlice output. Doing this I can do my custom processing and map many signals to the registered slices.

**Comment by PolarBean** [comment]
I have code to do exactly this. 
```python
def generate_target_slice(alignment, volume):
    Ox, Oy, Oz, Ux, Uy, Uz, Vx, Vy, Vz = alignment
    ##just for mouse for now should switch to fetch from volume shape
    bounds = [455, 527, 319]
    X_size = np.sqrt(np.sum(np.square((Ux, Uy, Uz))))
    Z_size = np.sqrt(np.sum(np.square((Vx, Vy, Vz))))

    X_size = np.round(X_size).astype(int)
    Z_size = np.round(Z_size).astype(int)

    Uarange = np.arange(0, 1, 1 / X_size)
    Varange = np.arange(0, 1, 1 / Z_size)
    Ugrid, Vgrid = np.meshgrid(Uarange, Varange)
    Ugrid_x = Ugrid * Ux
    Ugrid_y = Ugrid * Uy
    Ugrid_z = Ugrid * Uz
    Vgrid_x = Vgrid * Vx
    Vgrid_y = Vgrid * Vy
    Vgrid_z = Vgrid * Vz

    X_Coords = (Ugrid_x + Vgrid_x).flatten() + Ox
    Y_Coords = (Ugrid_y + Vgrid_y).flatten() + Oy
    Z_Coords = (Ugrid_z + Vgrid_z).flatten() + Oz

    X_Coords = np.round(X_Coords).astype(int)
    Y_Coords = np.round(Y_Coords).astype(int)
    Z_Coords = np.round(Z_Coords).astype(int)

    out_bounds_Coords = (
        (X_Coords > bounds[0])
        | (Y_Coords > bounds[1])
        | (Z_Coords > bounds[2])
        | (X_Coords < 0)
        | (Y_Coords < 0)
        | (Z_Coords < 0)
    )
    X_pad = X_Coords.copy()
    Y_pad = Y_Coords.copy()
    Z_pad = Z_Coords.copy()

    X_pad[out_bounds_Coords] = 0
    Y_pad[out_bounds_Coords] = 0
    Z_pad[out_bounds_Coords] = 0

    regions = volume[X_pad, Y_pad, Z_pad]

    ##this is a quick hack to solve rounding errors
    C = len(regions)
    compare = C - X_size * Z_size
    # if x is off by one
    if abs(compare) == X_size:
        if compare > 0:
            Z_size += 1
        if compare < 0:
            Z_size -= 1
    # if z is off by one
    elif abs(compare) == Z_size:
        if compare > 0:
            X_size += 1
        if compare < 0:
            X_size -= 1
    # if both are off by one in the same direction
    elif abs(compare) == X_size + Z_size + 1:
        if compare > 0:
            Z_size += 1
            X_size += 1
        if compare < 0:
            Z_size -= 1
            X_size -= 1

    regions = regions.reshape((abs(Z_size), abs(X_size)))
    return regions

```

It expects a 3d volume but you can load the allen one using nibabel. Usage of this function would look like this:
```python

import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt

volume_path = r"allenSTPT.nii"
volume = nib.load(volume_path)
volume = np.array(volume.get_fdata())
alignment = [ 404,24,285,-353,-3,-1,-12,-18,-277]
slice = generate_target_slice(alignment, volume)
plt.imshow(slice)
plt.show()
```

**Comment by PolarBean** [comment]
This slices any nii volume which is in allen CCF space

**Comment by JulesScholler** [comment]
May I ask you which atlas did you use? Or its orientation? Your code is working but I can't find the right slice and I think it is linked to the orientation (I don't want to manually try all possible combination of rotation and mirroring..) 

Thanks!

**Comment by PolarBean** [comment]
You need a ccf atlas with a resolution of 25 microns per pixel. To make sure its in the CCF space get them from the allen here 
http://download.alleninstitute.org/informatics-archive/current-release/mouse_ccf/
They have a few volumes depending on what you would like (these are stpt, nissl, and the delineations you can view in QuickNII)

**Comment by JulesScholler** [comment]
The atlas shape is indeed not matching yours [455, 527, 319]. The cff atlas shape is [527, 319, 455]. It seems to me that QuickNII does not use the same axis order, or a different orientation. When I open in QuickNII I have a completely different output (which is the right one) than when using your slicing function (which gives wrong slice). On the paper the reference figure for orientation is this:

![image](https://user-images.githubusercontent.com/23705332/197720660-142d4051-9769-4079-b941-d97ff4df3086.png)

I can't make sens of it since in python (and any programming language) the origin of an array is the top left. It would have been easier to name axis (0,1,2) so I understand how x in this image (and QuickNII) relates to the CFF array. My guess is that there is a combination of axis swap and a mirroring along 'z' to take into account the origin.

**Comment by PolarBean** [comment]
I suppose that is true, QuickNII must have a different orientation. I just opened up the nrrd volume and had a look. here is how you may solve your issue. 
```python
import nrrd
readdata, header = nrrd.read('ara_nissl_25.nrrd')
readdata_transposed = np.transpose(readdata, (2,0,1))
```
you could then either write this to a nii or just use it like this directly. Not sure why QuickNII does this and I suppose I must have retrieved the same volume that QuickNII uses.

**Comment by PolarBean** [comment]
install pynrrd to run the above code

**Comment by JulesScholler** [comment]
Thanks a lot @PolarBean!

It worked by adding `readdata_transposed_mirrored = readdata_transposed[:, :, ::-1]` and I have now the same overlay as in QuickNII.

**Comment by PolarBean** [comment]
No worries i'll make this more clear in the documentation :)
