### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by ZoeyZhouZhou** [PolarBean/DeepSlice#22]
#When I created DS-CPU or DS-GPU, always got  "Solving environment: failed".
#Could you please help me to solve this issue?
#MacBook Air M1

conda_environments % conda env create -f DS-GPU.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - setuptools==61.2.0=py37haa95532_0
  - certifi==2022.5.18.1=py37haa95532_0
  - wincertstore==0.2=py37haa95532_2
  - openssl==1.1.1o=h2bbff1b_0
  - vs2015_runtime==14.27.29016=h5e58377_2
  - sqlite==3.38.3=h2bbff1b_0
  - vc==14.2=h21ff451_1
  - pip==21.2.4=py37haa95532_0
  - cudnn==7.6.0=cuda10.0_0
  - python==3.7.13=h6244533_0
  - ca-certificates==2022.4.26=haa95532_0
  - cudatoolkit==10.0.130=0

**Comment by PolarBean** [comment]
hmm, this is likely as the environment was not exported on an M1 mac.
referring to this [stackoverflow question](https://stackoverflow.com/questions/72964800/what-is-the-proper-way-to-install-tensorflow-on-apple-m1-in-2022)  it seems as though you're going to want to run 

`python -m pip install tensorflow-macos`

Then you'll likely want to try and import DeepSlice and if it raises an exception import the missing package, rinse and repeat. If I had an m1 I would try and make a compatible environment yaml however I don't.
let me know how you go!

all the best, 

Harry

**Comment by ZoeyZhouZhou** [comment]
Hi Harry, thank you so much for your applying，I just find the online BrainSlice is recovered,  I can use it dirrectly! 
There is actually so many bugs with the M1 system. Maybe I should change one.

Thanks again and have a nice day!

Zoey
