### ISSUE TITLE
Something went wrong on https://www.deepslice.com.au/ 

### ISSUE THREAD

**Issue by ablot** [PolarBean/DeepSlice#23]
The site seems to be down with a "Something went wrong" page. Did you stop supporting it or is that a temporary incident?

Thanks!

**Comment by ablot** [comment]
Thanks that was very fast!
There might still be an issue. I tried to run one small dataset and got:

```
AN ERROR HAS OCCURRED
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error

```

Could it be that my dataset is ill formated? The data looked ok in ABBA.

**Comment by PolarBean** [comment]
OK I think I've solved it (for real this time).  Please try again with your dataset and let me know the result

**Comment by ablot** [comment]
Partial success!

Deepslice seems to run but I cannot see the atlas in the results page.
 
![Screenshot 2022-12-07 at 18 31 33](https://user-images.githubusercontent.com/2701493/206266486-05c89a75-7f82-45c1-8c93-4b07ad6ef938.png)

but the xml output is good (here as load in ABBA):
![Screenshot 2022-12-07 at 18 34 19](https://user-images.githubusercontent.com/2701493/206266871-1df3737b-b120-4c6c-b192-9dd7597c757d.png)

**Comment by ablot** [comment]
Thanks a lot! Great piece of software!
The only remaining issue is that the results of running DeepSlice locally are very different (aka bad) but I'll dig more in the doc existing /existing issues and open a new one if I cannot find what I did wrong.
