### ISSUE TITLE
Upload the half photo on DeepSlice

### ISSUE THREAD

**Issue by ZoeyZhouZhou** [PolarBean/DeepSlice#24]
Hi，Harry，
I have another question about the DeepSlice.
Because of the time-consuming of one confocal photo for whole brain. is it necessary to take the photo for the whole slice? Or I can just scan half of the brain slice especially in the coronal orientation. It can directly save half time. But seemly that I cannot upload photos like that.
May be it can be renewed. Or It is my fault not finding the correct method.

I am looking forward for your kind replying 
Best wishes for your life!

Zoey

**Comment by PolarBean** [comment]
Hi Zoey, 

we do not support hemisections. If possible you could take a low resolution image of the slide and use this for deepslice. Aligning your tissue in this way. Else, QuickNii supports fully manual registrations of hemi sections.

all the best,

Harry

**Comment by ZoeyZhouZhou** [comment]
Harry, thank you for your advice， It really works for me!！
