### ISSUE TITLE
Local run of deepslice performs poorly

### ISSUE THREAD

**Issue by ablot** [PolarBean/DeepSlice#26]
I have  a dataset that was quite well registered by the web based DeepSlice. When I try to clone the repository and run the DeepSlice_example.ipynb with my dataset, I get a very poor registration. Can it be because the arguments are slightly different or is it the trained model that is different?
For the arguments are:
- `Normalise section angles` equivalent to `Model.predict(prop_angles=True)`
- `Slower but ..` is `wise=True`
- Is `huber` used in the web version?

Thanks!

**Comment by PolarBean** [comment]
Its because the web version of DeepSlice is more recent, we are resolving these issues now and will have the github updated soon. Thank you for your patience

**Comment by PolarBean** [comment]
This is now fixed! as of #29 Try it out :) We will release on pypi soon
