### ISSUE TITLE
Something Went Wrong - Website appears to be down

### ISSUE THREAD

**Issue by TacticBlack** [PolarBean/DeepSlice#28]
Went to https://www.deepslice.com.au/ and screenshot the following:
![SomethingWrong](https://user-images.githubusercontent.com/79601721/217930084-9d72c949-0eee-4977-9bce-144f0163b2b9.PNG)

The website is not currently working.

**Comment by PolarBean** [comment]
It'll be back in a few hours! Sorry!

**Comment by PolarBean** [comment]
Back :)
