### ISSUE TITLE
Make PyPI release from CI

### ISSUE THREAD

**Issue by andreped** [PolarBean/DeepSlice#30]
Noticed you were having some issues with making PyPI releases from CI workflows.

You can take a look how we did it in this project:
https://github.com/EIDOSLAB/torchstain/blob/main/.github/workflows/build.yaml

Or this project:
https://github.com/andreped/GradientAccumulator/blob/main/.github/workflows/build_release.yml

Works great!

**Comment by andreped** [comment]
If you want to make github release AND make PyPI release in the same CI workflow, this is probably what you want:
https://github.com/smistad/FAST/blob/master/.github/workflows/CI-ubuntu.yml#L129

Hope it works out!

**Comment by PolarBean** [comment]
Thank you, sorry for spamming your github feed I hadn't thought of that.
I'll check out your workflows to see what you did. 

I have the basic push to PyPi on release with the tag as version number working as of a minute ago though :) https://pypi.org/project/DeepSlice/

**Comment by PolarBean** [comment]
Yes no more 11 releases a day for the immediate future 🙃
