### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by DavidBarriere** [PolarBean/DeepSlice#33]
Dear DeepSlice Team

Installation process failed on my ubuntu 20.04LTS due to conflicting dependencies using pip: 

ERROR: Cannot install deepslice==1.0.0, deepslice==1.0.1, deepslice==1.0.11, deepslice==1.0.2, deepslice==1.0.3, deepslice==1.0.4, deepslice==1.0.5, deepslice==1.0.6, deepslice==1.1.0 and deepslice==1.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    deepslice 1.1.1 depends on tensorflow==1.15.0
    deepslice 1.1.0 depends on tensorflow==1.15.0
    deepslice 1.0.11 depends on tensorflow==1.15.0
    deepslice 1.0.6 depends on tensorflow==1.15.0
    deepslice 1.0.5 depends on tensorflow==1.15.0
    deepslice 1.0.4 depends on tensorflow==1.15.0
    deepslice 1.0.3 depends on tensorflow==1.15.0
    deepslice 1.0.2 depends on tensorflow==1.15.0
    deepslice 1.0.1 depends on tensorflow==1.15.0
    deepslice 1.0.0 depends on tensorflow==1.15.0

**Comment by PolarBean** [comment]
Looks like you're not installing from an environment which has python 3.7. If you use conda you can create a fresh environment like such. 
`conda create --name env_name python=3.7

pip install DeepSlice`

**Comment by DavidBarriere** [comment]
I currently use python 3.7
dbarriere@dbarriere-Precision-7560:~$ python -V
Python 3.7.16

**Comment by DavidBarriere** [comment]
Okay it seems working :+1: 
Thank you

**Comment by PolarBean** [comment]
Great! If you have any other questions or want to contribute in terms of suggestions for improvement just let me know :)
