### ISSUE TITLE
 "No section number found in filename"

### ISSUE THREAD

**Issue by lanzaix** [PolarBean/DeepSlice#37]
Hi I followed the documentation and tried to run some slices. The program can  "Found 2 validated image filenames." but no matter how I changed the file name it kept telling me  "No section number found in filename" even I named it like "section_numbers_1.jpg". What could be the reason? Thanks a lot!

**Comment by PolarBean** [comment]
glad you solved it! if anyone else comes across this it is because you should have the section number in the filename as _'sXXX'. DeepSlice looks for this during the angle integration as well even though it doesnt need to so I should probably patch this.
