### ISSUE TITLE
Supporting tiff

### ISSUE THREAD

**Issue by lanzaix** [PolarBean/DeepSlice#38]
Hi when I read the documentation/guide it says DS supports tiff but when it won't recognize them when I actually ran the code. Besides manually converting the files, is there any other solution? Thank you!

**Comment by PolarBean** [comment]
It does support tiff last I checked but the model does not support 16 bit images, so its best to first scale it to 8 bit (make sure your images still look reasonable and they dont have a bunch of saturated pixels). I don't believe QuickNII supports tiff so it will be difficult to view your results. I would recommend converting them to png unless you really want to stick to tiff :)
