### ISSUE TITLE
Got wrong results from DS-GPU 1.1.2 on my own PC

### ISSUE THREAD

**Issue by BinZJU** [PolarBean/DeepSlice#39]
Hey, thanks for developing such powerful tools. I know the website https://www.deepslice.com.au/ has provided an easy way to align the slices. Yet, I have to use it offline sometimes. So I installed DS-GPU 1.1.2 in my own PC. To validate it, I aligned 35 slices in GLTa folder with DS-GPU, which gave a wrong result as attached. All the depths predicted were around 438. However, when uploading the same 35 slices to the web interface, I got the right result, with depths ranging from 48 to 422.
Could you please help me with the troubleshooting?
Thank you again.

BTW, the s104 slice has been renamed as 641_2002_2568_NM01_s104, whose original name is 641_2002_2567_NM01_s104.

![image](https://github.com/PolarBean/DeepSlice/assets/70118908/93168843-068c-42e1-9eb9-94ac1ad598d6)

[DS-GPU-Results.csv](https://github.com/PolarBean/DeepSlice/files/11778493/DS-GPU-Results.csv)

**Comment by PolarBean** [comment]
thats strange, are you using the latest version of DeepSlice either installed via `pip install --upgrade DeepSlice` or from the github repo?

**Comment by BinZJU** [comment]
> thats strange, are you using the latest version of DeepSlice either installed via `pip install --upgrade DeepSlice` or from the github repo?

I've tried both. The results are quite odd.

**Comment by PolarBean** [comment]
Did you download the images from the website?

**Comment by BinZJU** [comment]
Sorry for the delayed reply. I have been occupied with other experiments. I will try again and let you know ASAP. During the previous trial, I used the images in the GLTa folder, extracted from the file Deepslice-1.1.2.zip.

**Comment by BinZJU** [comment]
> Did you download the images from the website? I just tried with them and it worked for me

I've removed the conda env and re-installed DS-GPU again. However, the error was not fixed. Do you have any recommendations?

**Comment by PolarBean** [comment]
Its difficult since i cant replicate your problem. If you would like we can set up a zoom call and go through it together? my email is harry.carey@medisin.uio.no

**Comment by PolarBean** [comment]
After our meeting we determined that the issue likely came from some CUDA incomptaibility. The machine was using CUDA version 12.1. To fix this we placed 
```python 
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
```
at the beginning of the script. After which it ran correctly
