### ISSUE TITLE
XML not saving from anaconda prompt

### ISSUE THREAD

**Issue by sadinoj** [PolarBean/DeepSlice#42]
Hi, thank you for making DeepSlice, it's been very handy! 
I ran DeepSlice through anaconda prompt and it was able to save the csv and the json file but the xml file does not save. When I go to open the json file in QuickNii the original image is not displayed under the atlas predictions. Ideally I would like to do a manual check in quicknii where I compare the original image to the DeepSlice atlas prediction and make adjustments as necessary. The predictions are what I would expect but I can't easily verify that without seeing the original image underneath the atlas. 
I tried running images in the web interface and saved all three files (csv, json, xml) then opened the xml in quicknii. It opens and I can see the images underneath the atlas but the atlas predictions are not accurate at all. The json saved from the web application has the same issue. I'm not sure on which end something is wrong (deepslice or quicknii) because I've successfully used this workflow in the past for a different project. 
Thank you in advance for your help!

**Comment by PolarBean** [comment]
Hi! thanks for using DeepSlice :) we are in the process of phasing out the XML, but the most recent update to DeepSlice fixes some issues with it. Still, the json should load. The most likely reason is that the filenames in the json have some path which is not the same as the path to the images relative to the json. Could you please paste the json here so that I may inspect it?

**Comment by sadinoj** [comment]
Thanks for the quick response! I do keep all of my images on an external server so that might causing a path problem. But of course the "filepath" argument points to the correct place and the json is saved to the same place as the images. Here is an example json file: 
{"name": "", "target": "ABA_Mouse_CCFv3_2017_25um.cutlas", "aligner": "prerelease_1.0.0", "slices": [{"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_19_1_Maximum_DAPI_scaled_s19.png", "anchoring": [371.9182586669922, 122.27445793151855, 270.6842803955078, -274.74708557128906, 0.5023435354232788, -9.526942729949951, 14.138421535491943, -4.656795263290405, -213.21941375732422], "height": 756, "width": 1124, "nr": 19, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_20_1_Maximum_DAPI_scaled_s20.png", "anchoring": [403.2600860595703, 315.45062255859375, 277.029541015625, -338.3686065673828, -3.1655847132205963, 3.052344262599945, -6.957581043243408, 10.833151459693909, -224.50184631347656], "height": 756, "width": 1308, "nr": 20, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_21_1_Maximum_DAPI_scaled_s21.png", "anchoring": [346.4236297607422, 323.8828582763672, 258.98814392089844, -245.85215759277344, -9.896559834480286, 31.46324634552002, -41.869197845458984, 8.788307309150696, -224.21665954589844], "height": 756, "width": 756, "nr": 21, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_22_1_Maximum_DAPI_scaled_s22.png", "anchoring": [401.1753692626953, 322.00636291503906, 282.8162384033203, -334.8154602050781, -2.575323224067688, -11.071011066436768, 15.100085258483887, -12.236627101898193, -237.86762237548828], "height": 756, "width": 1308, "nr": 22, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_23_1_Maximum_DAPI_scaled_s23.png", "anchoring": [408.0019989013672, 311.9775695800781, 298.61521911621094, -341.35194396972656, -8.148613214492798, 20.29560089111328, -9.847406387329102, 23.246290683746338, -279.4923095703125], "height": 941, "width": 1308, "nr": 23, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_24_1_Maximum_DAPI_scaled_s24.png", "anchoring": [408.6247100830078, 334.47789001464844, 297.3105010986328, -348.6504821777344, -1.640476018190384, 8.93699598312378, -1.9978294372558594, 18.30418109893799, -278.645751953125], "height": 941, "width": 1308, "nr": 24, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_25_1_Maximum_DAPI_scaled_s25.png", "anchoring": [401.4193878173828, 341.2948303222656, 317.4881896972656, -346.37770080566406, 2.4876382052898407, -19.77882671356201, 13.6582932472229, 5.736444473266602, -290.1858367919922], "height": 940, "width": 1307, "nr": 25, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_26_1_Maximum_DAPI_scaled_s26.png", "anchoring": [400.78717041015625, 344.06028747558594, 313.75709533691406, -336.41664123535156, 10.949596017599106, -14.421223640441895, 10.393211364746094, 10.154701232910156, -288.4764709472656], "height": 940, "width": 1308, "nr": 26, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_27_1_Maximum_DAPI_scaled_s27.png", "anchoring": [389.8696594238281, 351.34352111816406, 318.17884826660156, -339.6985321044922, -2.5350732803344727, -20.87980842590332, 14.485322952270508, 6.9649306535720825, -284.0455017089844], "height": 940, "width": 1308, "nr": 27, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_28_1_Maximum_DAPI_scaled_s28.png", "anchoring": [430.1293029785156, 342.9808349609375, 287.1270294189453, -369.0507354736328, -7.330575227737427, 34.16914463043213, -20.79041862487793, 12.805586457252502, -285.49786376953125], "height": 939, "width": 1492, "nr": 28, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_29_1_Maximum_DAPI_scaled_s29.png", "anchoring": [426.7367248535156, 349.32606506347656, 299.1401672363281, -387.59349060058594, -7.512643814086914, 11.938132762908936, -4.626748323440552, 7.723955273628235, -288.1368865966797], "height": 940, "width": 1492, "nr": 29, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_30_1_Maximum_DAPI_scaled_s30.png", "anchoring": [438.1760559082031, 362.55908203125, 289.6688232421875, -372.21434020996094, -6.184488415718079, 36.384854316711426, -24.740670204162598, 1.2455862760543823, -273.9782409667969], "height": 941, "width": 1308, "nr": 30, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_31_1_Maximum_DAPI_scaled_s31.png", "anchoring": [430.2766876220703, 362.1724853515625, 297.03623962402344, -383.8478088378906, -7.384878635406494, 10.887706995010376, -7.152410984039307, -1.1557637453079224, -290.1578826904297], "height": 940, "width": 1492, "nr": 31, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_32_1_Maximum_DAPI_scaled_s32.png", "anchoring": [424.78431701660156, 368.51629638671875, 316.1370391845703, -394.6168212890625, -11.055397033691406, -14.535436153411865, 11.867242336273193, -6.068334698677063, -295.7567901611328], "height": 940, "width": 1492, "nr": 32, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_33_1_Maximum_DAPI_scaled_s33.png", "anchoring": [438.1413269042969, 380.22174072265625, 304.7324981689453, -402.1219024658203, -6.4887166023254395, 13.708311557769775, -10.932451248168945, 2.1306246519088745, -308.3710174560547], "height": 940, "width": 1492, "nr": 33, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_34_1_Maximum_DAPI_scaled_s34.png", "anchoring": [440.7698974609375, 363.9647979736328, 299.3851776123047, -386.36732482910156, 0.20629143714904785, 25.42878532409668, -23.78115463256836, -12.653446197509766, -296.45884704589844], "height": 940, "width": 1491, "nr": 34, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_35_1_Maximum_DAPI_scaled_s35.png", "anchoring": [443.02671813964844, 370.6017150878906, 297.25726318359375, -395.70135498046875, -4.468079328536987, 26.789848804473877, -17.925984621047974, 13.89720630645752, -312.28965759277344], "height": 1124, "width": 1676, "nr": 35, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_36_1_Maximum_DAPI_scaled_s36.png", "anchoring": [434.44053649902344, 389.35205078125, 299.1642303466797, -397.23768615722656, -18.687413692474365, 9.700198650360107, -5.597282648086548, 0.5779538750648499, -279.53880310058594], "height": 940, "width": 1491, "nr": 36, "markers": []}, {"filename": "DeepSlice_scaledImages\\20230406_EdU647ASPACy3_4314_37_1_Maximum_DAPI_scaled_s37.png", "anchoring": [411.6184997558594, 399.18016052246094, 312.7837219238281, -374.5419158935547, -9.98676872253418, -3.99479603767395, 5.497797131538391, -16.808839797973633, -269.70201110839844], "height": 940, "width": 1492, "nr": 37, "markers": []}]}

**Comment by PolarBean** [comment]
Thanks! What I can see from the json is that the images are saved in a folder called DeepSlice_scaledImages/ please put the json file outside this folder :) DeepSlice will look in this folder for the images

**Comment by sadinoj** [comment]
That worked! Thank you :)
