### ISSUE TITLE
Installing DeepSlice on macos M1 (arm64)

### ISSUE THREAD

**Issue by anna-teruel** [PolarBean/DeepSlice#48]
Hey! I'm trying to install this tool on macos arm64 architecture. I guess this package is not implemented for this kind of architecture. 

I created a new environment with intelx86 miniconda, and used python 3.7 as you described (this version is not available for arm64 architecture). After creating the environment, I installed DeepSlice via pip. 

Although I think I successfully installed it (`pip list` `DeepSlice 1.1.6`), when I try  to import DeepSlice: `zsh: illegal hardware instruction python`. I get same error when I try to `import tensorflow as tf`.

If I use jupyter notebook on visual studio code, and I try to `from DeepSlice improt DSModel`, I get `Running cells with 'DeepSlice' requires the ipykernel package.
Run the following command to install 'ipykernel' into the Python environment. 
Command: 'conda install -n DeepSlice ipykernel --update-deps --force-reinstall'`
Although I run the suggested command, I get this error continuously. 

If I try to use the conda file provided in the repository, I get following errors:
`(base) annateruel@MacBook-MacBook-Pro-de-Anna conda_environments % conda env create -f DS-CPU.yml
Channels:
 - defaults
 - conda-forge
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: | warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
/ warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed
Channels:
 - defaults
 - conda-forge
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: \ warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
/ warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested _openmp_mutex ==4.5 1_gnu
  - nothing provides requested aiohttp ==3.8.1 py37h7f8727e_0
  - nothing provides requested anyio ==3.5.0 py37h06a4308_0
  - nothing provides requested argon2-cffi-bindings ==21.2.0 py37h7f8727e_0
  - nothing provides requested astor ==0.8.1 py37h06a4308_0
  - nothing provides requested blinker ==1.4 py37h06a4308_0
  - nothing provides requested blosc ==1.21.0 h8c45485_0
  - nothing provides requested bottleneck ==1.3.4 py37hce1f21e_0
  - nothing provides requested brotli ==1.0.9 he6710b0_2
  - nothing provides requested brotlipy ==0.7.0 py37h27cfd23_1003
  - nothing provides requested brunsli ==0.1 h2531618_0
  - nothing provides requested bzip2 ==1.0.8 h7b6447c_0
  - nothing provides requested c-ares ==1.18.1 h7f8727e_0
  - nothing provides requested ca-certificates ==2022.4.26 h06a4308_0
  - nothing provides requested certifi ==2022.5.18.1 py37h06a4308_0
  - nothing provides requested cffi ==1.15.0 py37hd667e15_1
  - nothing provides requested cfitsio ==3.470 hf0d0db6_6
  - nothing provides requested charls ==2.2.0 h2531618_0
  - nothing provides requested cryptography ==36.0.0 py37h9ce1e76_0
  - nothing provides requested curl ==7.80.0 h7f8727e_0
  - nothing provides requested cytoolz ==0.11.0 py37h7b6447c_0
  - nothing provides requested debugpy ==1.5.1 py37h295c915_0
  - nothing provides requested expat ==2.4.4 h295c915_0
  - nothing provides requested freetype ==2.11.0 h70c0345_0
  - nothing provides requested frozenlist ==1.2.0 py37h7f8727e_0
  - nothing provides requested gettext ==0.21.0 hf68c758_0
  - nothing provides requested giflib ==5.2.1 h7b6447c_0
  - nothing provides requested git ==2.34.1 pl5262hc120c5b_0
  - nothing provides requested grpcio ==1.42.0 py37hce63b2e_0
  - nothing provides requested h5py ==2.10.0 py37hd6299e0_1
  - nothing provides requested hdf5 ==1.10.6 hb1b8bf9_0
  - nothing provides requested icu ==58.2 he6710b0_3
  - nothing provides requested imagecodecs ==2021.8.26 py37h4cda21f_0
  - nothing provides requested importlib-metadata ==4.8.2 py37h06a4308_0
  - nothing provides requested intel-openmp ==2021.4.0 h06a4308_3561
  - nothing provides requested ipykernel ==6.4.1 py37h06a4308_1
  - nothing provides requested ipython ==7.31.1 py37h06a4308_0
  - nothing provides requested jpeg ==9d h7f8727e_0
  - nothing provides requested jupyter_core ==4.9.1 py37h06a4308_0
  - nothing provides requested jxrlib ==1.1 h7b6447c_2
  - nothing provides requested kiwisolver ==1.3.2 py37h295c915_0
  - nothing provides requested krb5 ==1.19.2 hac12032_0
  - nothing provides requested lcms2 ==2.12 h3be6417_0
  - nothing provides requested ld_impl_linux-64 ==2.35.1 h7274673_9
  - nothing provides requested lerc ==3.0 h295c915_0
  - nothing provides requested libaec ==1.0.4 he6710b0_1
  - nothing provides requested libcurl ==7.80.0 h0b77cf5_0
  - nothing provides requested libdeflate ==1.8 h7f8727e_5
  - nothing provides requested libedit ==3.1.20210910 h7f8727e_0
  - nothing provides requested libev ==4.33 h7f8727e_1
  - nothing provides requested libffi ==3.3 he6710b0_2
  - nothing provides requested libgcc-ng ==9.3.0 h5101ec6_17
  - nothing provides requested libgfortran-ng ==7.5.0 ha8ba4b0_17
  - nothing provides requested libgfortran4 ==7.5.0 ha8ba4b0_17
  - nothing provides requested libgomp ==9.3.0 h5101ec6_17
  - nothing provides requested libnghttp2 ==1.46.0 hce63b2e_0
  - nothing provides requested libpng ==1.6.37 hbc83047_0
  - nothing provides requested libprotobuf ==3.19.1 h4ff587b_0
  - nothing provides requested libsodium ==1.0.18 h7b6447c_0
  - nothing provides requested libssh2 ==1.9.0 h1ba5d50_1
  - nothing provides requested libstdcxx-ng ==9.3.0 hd4cf53a_17
  - nothing provides requested libtiff ==4.1.0 h2733197_1
  - nothing provides requested libwebp ==1.2.0 h89dd481_0
  - nothing provides requested libxml2 ==2.9.12 h03d6c58_0
  - nothing provides requested libxslt ==1.1.34 hc22bd24_0
  - nothing provides requested libzopfli ==1.0.3 he6710b0_0
  - nothing provides requested locket ==0.2.1 py37h06a4308_1
  - nothing provides requested lxml ==4.8.0 py37h1f438cf_0
  - nothing provides requested lz4-c ==1.9.3 h295c915_1
  - nothing provides requested markdown ==3.3.4 py37h06a4308_0
  - nothing provides requested markupsafe ==2.0.1 py37h27cfd23_0
  - nothing provides requested matplotlib-base ==3.5.1 py37ha18d171_0
  - nothing provides requested mistune ==0.8.4 py37h14c3975_1001
  - nothing provides requested mkl ==2021.4.0 h06a4308_640
  - nothing provides requested mkl-service ==2.4.0 py37h7f8727e_0
  - nothing provides requested mkl_fft ==1.3.1 py37hd3c417c_0
  - nothing provides requested mkl_random ==1.2.2 py37h51133e4_0
  - nothing provides requested multidict ==5.2.0 py37h7f8727e_2
  - nothing provides requested nbconvert ==6.3.0 py37h06a4308_0
  - nothing provides requested ncurses ==6.3 h7f8727e_2
  - nothing provides requested notebook ==6.4.8 py37h06a4308_0
  - nothing provides requested numexpr ==2.8.1 py37h6abb31d_0
  - nothing provides requested openjpeg ==2.4.0 h3ad879b_0
  - nothing provides requested openssl ==1.1.1o h7f8727e_0
  - nothing provides requested pcre2 ==10.37 he7ceb23_1
  - nothing provides requested perl ==5.26.2 h14c3975_0
  - nothing provides requested pillow ==8.4.0 py37h5aabda8_0
  - nothing provides requested pip ==21.2.2 py37h06a4308_0
  - nothing provides requested protobuf ==3.19.1 py37h295c915_0
  - nothing provides requested pyrsistent ==0.18.0 py37heee7806_0
  - nothing provides requested pysocks ==1.7.1 py37_1
  - nothing provides requested python ==3.7.11 h12debd9_0
  - nothing provides requested pywavelets ==1.1.1 py37h7b6447c_2
  - nothing provides requested pyyaml ==6.0 py37h7f8727e_1
  - nothing provides requested pyzmq ==22.3.0 py37h295c915_2
  - nothing provides requested readline ==8.1.2 h7f8727e_1
  - nothing provides requested scikit-image ==0.17.2 py37hdf5156a_0
  - nothing provides requested scikit-learn ==0.23.2 py37h0573a6f_0
  - nothing provides requested scipy ==1.7.3 py37hc147768_0
  - nothing provides requested setuptools ==58.0.4 py37h06a4308_0
  - nothing provides requested snappy ==1.1.8 he6710b0_0
  - nothing provides requested sniffio ==1.2.0 py37h06a4308_1
  - nothing provides requested sqlite ==3.37.2 hc218d9a_0
  - nothing provides requested tensorflow ==2.2.0 mkl_py37h6e9ce2d_0
  - nothing provides requested tensorflow-base ==2.2.0 mkl_py37hd506778_0
  - nothing provides requested termcolor ==1.1.0 py37h06a4308_1
  - nothing provides requested terminado ==0.13.1 py37h06a4308_0
  - nothing provides requested tk ==8.6.11 h1ccaba5_0
  - nothing provides requested tornado ==6.1 py37h27cfd23_0
  - nothing provides requested websocket-client ==0.58.0 py37h06a4308_4
  - nothing provides requested wrapt ==1.13.3 py37h7f8727e_2
  - nothing provides requested xz ==5.2.5 h7b6447c_0
  - nothing provides requested yaml ==0.2.5 h7b6447c_0
  - nothing provides requested yarl ==1.6.3 py37h27cfd23_0
  - nothing provides requested zeromq ==4.3.4 h2531618_0
  - nothing provides requested zfp ==0.5.5 h295c915_6
  - nothing provides requested zlib ==1.2.11 h7f8727e_4
  - nothing provides requested zstd ==1.4.9 haebb681_0
  - package flask-1.1.2-pyhd3eb1b0_0 requires jinja2 >=2.10.1,<3.0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ _openmp_mutex ==4.5 1_gnu does not exist (perhaps a typo or a missing channel);
├─ aiohttp ==3.8.1 py37h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ anyio ==3.5.0 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ argon2-cffi-bindings ==21.2.0 py37h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ astor ==0.8.1 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ blinker ==1.4 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ blosc ==1.21.0 h8c45485_0 does not exist (perhaps a typo or a missing channel);
├─ bottleneck ==1.3.4 py37hce1f21e_0 does not exist (perhaps a typo or a missing channel);
├─ brotli ==1.0.9 he6710b0_2 does not exist (perhaps a typo or a missing channel);
├─ brotlipy ==0.7.0 py37h27cfd23_1003 does not exist (perhaps a typo or a missing channel);
├─ brunsli ==0.1 h2531618_0 does not exist (perhaps a typo or a missing channel);
├─ bzip2 ==1.0.8 h7b6447c_0 does not exist (perhaps a typo or a missing channel);
├─ c-ares ==1.18.1 h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ ca-certificates ==2022.4.26 h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ certifi ==2022.5.18.1 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ cffi ==1.15.0 py37hd667e15_1 does not exist (perhaps a typo or a missing channel);
├─ cfitsio ==3.470 hf0d0db6_6 does not exist (perhaps a typo or a missing channel);
├─ charls ==2.2.0 h2531618_0 does not exist (perhaps a typo or a missing channel);
├─ cryptography ==36.0.0 py37h9ce1e76_0 does not exist (perhaps a typo or a missing channel);
├─ curl ==7.80.0 h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ cytoolz ==0.11.0 py37h7b6447c_0 does not exist (perhaps a typo or a missing channel);
├─ debugpy ==1.5.1 py37h295c915_0 does not exist (perhaps a typo or a missing channel);
├─ expat ==2.4.4 h295c915_0 does not exist (perhaps a typo or a missing channel);
├─ flask ==1.1.2 pyhd3eb1b0_0 is installable and it requires
│  └─ jinja2 >=2.10.1,<3.0 , which can be installed;
├─ freetype ==2.11.0 h70c0345_0 does not exist (perhaps a typo or a missing channel);
├─ frozenlist ==1.2.0 py37h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ gettext ==0.21.0 hf68c758_0 does not exist (perhaps a typo or a missing channel);
├─ giflib ==5.2.1 h7b6447c_0 does not exist (perhaps a typo or a missing channel);
├─ git ==2.34.1 pl5262hc120c5b_0 does not exist (perhaps a typo or a missing channel);
├─ grpcio ==1.42.0 py37hce63b2e_0 does not exist (perhaps a typo or a missing channel);
├─ h5py ==2.10.0 py37hd6299e0_1 does not exist (perhaps a typo or a missing channel);
├─ hdf5 ==1.10.6 hb1b8bf9_0 does not exist (perhaps a typo or a missing channel);
├─ icu ==58.2 he6710b0_3 does not exist (perhaps a typo or a missing channel);
├─ imagecodecs ==2021.8.26 py37h4cda21f_0 does not exist (perhaps a typo or a missing channel);
├─ importlib-metadata ==4.8.2 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ intel-openmp ==2021.4.0 h06a4308_3561 does not exist (perhaps a typo or a missing channel);
├─ ipykernel ==6.4.1 py37h06a4308_1 does not exist (perhaps a typo or a missing channel);
├─ ipython ==7.31.1 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ jinja2 ==3.0.2 pyhd3eb1b0_0 is not installable because it conflicts with any installable versions previously reported;
├─ jpeg ==9d h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ jupyter_core ==4.9.1 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ jxrlib ==1.1 h7b6447c_2 does not exist (perhaps a typo or a missing channel);
├─ kiwisolver ==1.3.2 py37h295c915_0 does not exist (perhaps a typo or a missing channel);
├─ krb5 ==1.19.2 hac12032_0 does not exist (perhaps a typo or a missing channel);
├─ lcms2 ==2.12 h3be6417_0 does not exist (perhaps a typo or a missing channel);
├─ ld_impl_linux-64 ==2.35.1 h7274673_9 does not exist (perhaps a typo or a missing channel);
├─ lerc ==3.0 h295c915_0 does not exist (perhaps a typo or a missing channel);
├─ libaec ==1.0.4 he6710b0_1 does not exist (perhaps a typo or a missing channel);
├─ libcurl ==7.80.0 h0b77cf5_0 does not exist (perhaps a typo or a missing channel);
├─ libdeflate ==1.8 h7f8727e_5 does not exist (perhaps a typo or a missing channel);
├─ libedit ==3.1.20210910 h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ libev ==4.33 h7f8727e_1 does not exist (perhaps a typo or a missing channel);
├─ libffi ==3.3 he6710b0_2 does not exist (perhaps a typo or a missing channel);
├─ libgcc-ng ==9.3.0 h5101ec6_17 does not exist (perhaps a typo or a missing channel);
├─ libgfortran-ng ==7.5.0 ha8ba4b0_17 does not exist (perhaps a typo or a missing channel);
├─ libgfortran4 ==7.5.0 ha8ba4b0_17 does not exist (perhaps a typo or a missing channel);
├─ libgomp ==9.3.0 h5101ec6_17 does not exist (perhaps a typo or a missing channel);
├─ libnghttp2 ==1.46.0 hce63b2e_0 does not exist (perhaps a typo or a missing channel);
├─ libpng ==1.6.37 hbc83047_0 does not exist (perhaps a typo or a missing channel);
├─ libprotobuf ==3.19.1 h4ff587b_0 does not exist (perhaps a typo or a missing channel);
├─ libsodium ==1.0.18 h7b6447c_0 does not exist (perhaps a typo or a missing channel);
├─ libssh2 ==1.9.0 h1ba5d50_1 does not exist (perhaps a typo or a missing channel);
├─ libstdcxx-ng ==9.3.0 hd4cf53a_17 does not exist (perhaps a typo or a missing channel);
├─ libtiff ==4.1.0 h2733197_1 does not exist (perhaps a typo or a missing channel);
├─ libwebp ==1.2.0 h89dd481_0 does not exist (perhaps a typo or a missing channel);
├─ libxml2 ==2.9.12 h03d6c58_0 does not exist (perhaps a typo or a missing channel);
├─ libxslt ==1.1.34 hc22bd24_0 does not exist (perhaps a typo or a missing channel);
├─ libzopfli ==1.0.3 he6710b0_0 does not exist (perhaps a typo or a missing channel);
├─ locket ==0.2.1 py37h06a4308_1 does not exist (perhaps a typo or a missing channel);
├─ lxml ==4.8.0 py37h1f438cf_0 does not exist (perhaps a typo or a missing channel);
├─ lz4-c ==1.9.3 h295c915_1 does not exist (perhaps a typo or a missing channel);
├─ markdown ==3.3.4 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ markupsafe ==2.0.1 py37h27cfd23_0 does not exist (perhaps a typo or a missing channel);
├─ matplotlib-base ==3.5.1 py37ha18d171_0 does not exist (perhaps a typo or a missing channel);
├─ mistune ==0.8.4 py37h14c3975_1001 does not exist (perhaps a typo or a missing channel);
├─ mkl-service ==2.4.0 py37h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ mkl ==2021.4.0 h06a4308_640 does not exist (perhaps a typo or a missing channel);
├─ mkl_fft ==1.3.1 py37hd3c417c_0 does not exist (perhaps a typo or a missing channel);
├─ mkl_random ==1.2.2 py37h51133e4_0 does not exist (perhaps a typo or a missing channel);
├─ multidict ==5.2.0 py37h7f8727e_2 does not exist (perhaps a typo or a missing channel);
├─ nbconvert ==6.3.0 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ ncurses ==6.3 h7f8727e_2 does not exist (perhaps a typo or a missing channel);
├─ notebook ==6.4.8 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ numexpr ==2.8.1 py37h6abb31d_0 does not exist (perhaps a typo or a missing channel);
├─ openjpeg ==2.4.0 h3ad879b_0 does not exist (perhaps a typo or a missing channel);
├─ openssl ==1.1.1o h7f8727e_0 does not exist (perhaps a typo or a missing channel);
├─ pcre2 ==10.37 he7ceb23_1 does not exist (perhaps a typo or a missing channel);
├─ perl ==5.26.2 h14c3975_0 does not exist (perhaps a typo or a missing channel);
├─ pillow ==8.4.0 py37h5aabda8_0 does not exist (perhaps a typo or a missing channel);
├─ pip ==21.2.2 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ protobuf ==3.19.1 py37h295c915_0 does not exist (perhaps a typo or a missing channel);
├─ pyrsistent ==0.18.0 py37heee7806_0 does not exist (perhaps a typo or a missing channel);
├─ pysocks ==1.7.1 py37_1 does not exist (perhaps a typo or a missing channel);
├─ python ==3.7.11 h12debd9_0 does not exist (perhaps a typo or a missing channel);
├─ pywavelets ==1.1.1 py37h7b6447c_2 does not exist (perhaps a typo or a missing channel);
├─ pyyaml ==6.0 py37h7f8727e_1 does not exist (perhaps a typo or a missing channel);
├─ pyzmq ==22.3.0 py37h295c915_2 does not exist (perhaps a typo or a missing channel);
├─ readline ==8.1.2 h7f8727e_1 does not exist (perhaps a typo or a missing channel);
├─ scikit-image ==0.17.2 py37hdf5156a_0 does not exist (perhaps a typo or a missing channel);
├─ scikit-learn ==0.23.2 py37h0573a6f_0 does not exist (perhaps a typo or a missing channel);
├─ scipy ==1.7.3 py37hc147768_0 does not exist (perhaps a typo or a missing channel);
├─ setuptools ==58.0.4 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ snappy ==1.1.8 he6710b0_0 does not exist (perhaps a typo or a missing channel);
├─ sniffio ==1.2.0 py37h06a4308_1 does not exist (perhaps a typo or a missing channel);
├─ sqlite ==3.37.2 hc218d9a_0 does not exist (perhaps a typo or a missing channel);
├─ tensorflow-base ==2.2.0 mkl_py37hd506778_0 does not exist (perhaps a typo or a missing channel);
├─ tensorflow ==2.2.0 mkl_py37h6e9ce2d_0 does not exist (perhaps a typo or a missing channel);
├─ termcolor ==1.1.0 py37h06a4308_1 does not exist (perhaps a typo or a missing channel);
├─ terminado ==0.13.1 py37h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ tk ==8.6.11 h1ccaba5_0 does not exist (perhaps a typo or a missing channel);
├─ tornado ==6.1 py37h27cfd23_0 does not exist (perhaps a typo or a missing channel);
├─ websocket-client ==0.58.0 py37h06a4308_4 does not exist (perhaps a typo or a missing channel);
├─ wrapt ==1.13.3 py37h7f8727e_2 does not exist (perhaps a typo or a missing channel);
├─ xz ==5.2.5 h7b6447c_0 does not exist (perhaps a typo or a missing channel);
├─ yaml ==0.2.5 h7b6447c_0 does not exist (perhaps a typo or a missing channel);
├─ yarl ==1.6.3 py37h27cfd23_0 does not exist (perhaps a typo or a missing channel);
├─ zeromq ==4.3.4 h2531618_0 does not exist (perhaps a typo or a missing channel);
├─ zfp ==0.5.5 h295c915_6 does not exist (perhaps a typo or a missing channel);
├─ zlib ==1.2.11 h7f8727e_4 does not exist (perhaps a typo or a missing channel);
└─ zstd ==1.4.9 haebb681_0 does not exist (perhaps a typo or a missing channel).`

I don't know if there's any other Macos M1 user that has faced the same issues and could help. I would appreciate any help because I like this tool and I'm interested in using it.

**Comment by anna-teruel** [comment]
Hey! Because I cannot install it on my macOS, I've been using the website provided to align my brain slices. However, it hasn't been working for some days. Please, the error message from the attached screenshot. 

![Captura de pantalla 2024-01-29 a les 9 03 51](https://github.com/PolarBean/DeepSlice/assets/78961609/72361554-3a8b-4111-9a44-cb741effa694)

**Comment by PolarBean** [comment]
Hey the website is back online :) Unfortunately I do not have an arm mac so I cant trouble shoot installation on that platform.

**Comment by anna-teruel** [comment]
Thanks! I'll try to contribute implementing the package for m1

**Comment by PolarBean** [comment]
have you tried this? https://github.com/PolarBean/DeepSlice/issues/32#issuecomment-2038229502

**Comment by anna-teruel** [comment]
Yes, I have tried a similar approach. Unfortunately it didn't work for me. If I try to use your example notebook the kernel crashes when I try to import DSModel, like #50 . Running it from my python console I get >>> from DeepSlice import DSModel
zsh: illegal hardware instruction  python. For now, the approach from this issue #41  worked better for me. I just need the link to download the tf2 weights and finally test it on my mac m1. Thanks for checking and suggesting :)

**Comment by PolarBean** [comment]
Hey, DeepSlice now supports tf2, this may fix your issue
