### ISSUE TITLE
Kernel crashes when running "from DeepSlice import DSModel"

### ISSUE THREAD

**Issue by josh-steighner** [PolarBean/DeepSlice#50]
Hi, I installed DeepSlice and opened the example notebook in my default browser (Google Chrome) from terminal. The first few steps don't give me any issue, but when I run the import model step however, I get this error: "The kernel appears to have died. It will restart automatically." If I run the next step, I am told that "NameError: name 'DSModel' is not defined," indicating that the import step failed.

Is there a workaround for this, besides relying on the DeepSlice web version?
Thanks in advance for any advice!

**Comment by PolarBean** [comment]
It is hard to say without looking at your system. Did you install via pip?

**Comment by josh-steighner** [comment]
Yes, I used pip to do the install after using conda to make the environment and install python 3.7. I recall hearing somewhere that mixing conda and pip can cause issues, but that is mostly avoided by doing conda first and pip second (please correct me if that's wrong). I'm using a 2020 mac with an M1.

Here's everything I did up until opening the jupyter notebook:
`conda create --name DeepSlice`
`conda activate DeepSlice`
`conda config --env --set subdir osx-64`
`conda install python=3.7`
`pip install notebook`
`pip install jupyterlab`
`pip install DeepSlice`

**Comment by PolarBean** [comment]
ahh i havent tested on an m1. have you tried this? https://github.com/PolarBean/DeepSlice/issues/32#issuecomment-2038229502

**Comment by josh-steighner** [comment]
Hi, the comment you linked was actually my post from a couple weeks ago. I took a look at what worked for anna-teruel but have given up on getting it to work on my desktop for the time being and am using the website instead.

**Comment by josh-steighner** [comment]
Closing issue

**Comment by PolarBean** [comment]
fyi DeepSlice now supports more recent python versions. Perhaps this helps you.
