### ISSUE TITLE
DeepSlice Web won't run more than 25 images

### ISSUE THREAD

**Issue by jcs-01** [PolarBean/DeepSlice#55]
I uploaded 68 images to DeepSlice Web and once it hits 25, it just gets stuck. If I press reload, I get an xml file with 1-25 and #68, but nothing between 25-68. Is there a capacity limit? I have more than 25 scenes of the brain I'm trying to upload.

**Comment by jcs-01** [comment]
This might not actually be the problem--it gets stuck on image #24 when I run 25 images too.

**Comment by PolarBean** [comment]
Theres no limit like that. Quite strange. After you upload please wait for it to fully run. If it still doesn't work let me know
