### ISSUE TITLE
Compatibility Issue with DeepSlice Output and QuickNII: Unable to Load JSON Files

### ISSUE THREAD

**Issue by OlafTobark42** [PolarBean/DeepSlice#56]
Hello,

I've been successfully running DeepSlice via Conda and it works great. However, I've encountered an issue with the workflow integration. The prediction results from DeepSlice are generated in CSV and JSON formats. Unfortunately, the version of QuickNII I am using (QuickNII-ABAMouse-v3-2017 for macOS) in the "Manage Data" section does not support loading JSON files.

Currently, I am able to open the JSON files directly with VisuAlign, but I would prefer to use QuickNII for this step in my workflow. Is there a recommended solution for this issue? Would converting the JSON files to XML be advisable, or is there a possibility to include an XML export option in DeepSlice’s output?

Any advice or guidance on this matter would be greatly appreciated.

Thank you!

**Comment by PolarBean** [comment]
Oh I wasn't aware of this. @Tevemadar is there a workaround for this or should I add XML back to DeepSlice (I would rather not since the lxml library has many problems).

**Comment by Tevemadar** [comment]
I can reproduce the problem too. As a workaround, here's a converter for JSON files: https://www.nesys.uio.no/QuickNII/JSON2XML.html

**Comment by PolarBean** [comment]
Thanks!  Let us know if this is a good solution for you @OlafTobark42

**Comment by OlafTobark42** [comment]
Thank you for your prompt response and for providing the JSON to XML converter link. I tried the converter and was able to download the XML files and successfully open them with QuickNII. Although it's slightly cumbersome, this workaround effectively completes my workflow for now. There seems to be no need to add an XML output option to DeepSlice at this moment. I appreciate your support in resolving this issue! @PolarBean
