### ISSUE TITLE
Python version discrepancy 

### ISSUE THREAD

**Issue by cyf203** [PolarBean/DeepSlice#58]
Hi,
I am trying to install the DS. I found your readme suggests having Python 3.11. However, when I checked your conda environment file: DS-GPU.yml, I saw Python 3.7 was written. So, I wonder which one you suggest we go to?

Thank you,

**Comment by PolarBean** [comment]
Hey, I should remove the conda envs as they are no longer updated. Please go through pip and have Python 3.11
