### ISSUE TITLE
Will it work with a half of a picture?

### ISSUE THREAD

**Issue by khoroshyy** [PolarBean/DeepSlice#60]
Hi.
Is there any trick to using half pictures of a brain? 
Like the left or right part of a frontal section?
Thanks.
Petro.

**Comment by PolarBean** [comment]
Hi Petro, 

Unfortunately DeepSlice was not trained on hemisections though it is a popular request. It is possible to manually create an alignment for these sections using QuickNII.

**Comment by paulbrodersen** [comment]
FYI, it works brilliantly if you simply mirror the half slice.  https://github.com/paulbrodersen/coronal_hemisphere_annotation_tool

**Comment by PolarBean** [comment]
This is a clever workaround but theres a caveat, DeepSlice won't be able to accurately predict the angle if you have mirrored the section. DeepSlice assumes the sections position in the atlas is a 2D plane like this 

<img width="593" height="416" alt="Image" src="https://github.com/user-attachments/assets/47044ce3-6c4d-4c6d-bfb2-7b8458b5865f" />

However if you mirror it, the position of your section will look like this

<img width="681" height="360" alt="Image" src="https://github.com/user-attachments/assets/2258e921-2dd6-43ef-9165-c7670b1c9ec0" />

Which DeepSlice cannot predict, it will instead just find some flat plane that is not representative.

**Comment by paulbrodersen** [comment]
I agree that this is a potential problem, but in practice, people are usually pretty good at making coronal slices, so the error in the angle is likely small.

**Comment by PolarBean** [comment]
For an upcoming manuscript I have some related data (though I wasn't intending on answering this specific question). I chose 10 Allen ISH datasets based on the percentile of angle DeepSlice ranked them as (ie; one for each 10th percentile bin selected to represent both ML and DV angles). I then had humans align these for validation. This maybe was a bit overcomplicated but should be representative of real world angle distribution (though again that isn't what we were looking at in this study). 

The human predicted angles in these 10 datasets ranged from approx:

<img width="2547" height="1193" alt="Image" src="https://github.com/user-attachments/assets/df2e7bc4-0486-4174-915c-622beec17200" />

To:

<img width="2531" height="1197" alt="Image" src="https://github.com/user-attachments/assets/4ef2fbb2-f420-488e-9b8e-0200c08adb4a" />

**Comment by PolarBean** [comment]
Only the left vs right portion of that angle matters for the hemi brain mirroring. Similar results were shown in the DeepSlice paper where angles ranged from approx 

<img width="537" height="574" alt="Image" src="https://github.com/user-attachments/assets/bff0242b-331d-4009-b680-a2023a5b035f" />

very approximate but the largest angle in this graph is around -3 I think which appears like this 

<img width="2525" height="1196" alt="Image" src="https://github.com/user-attachments/assets/cbe6a83f-081a-4d2b-b615-2c46c268d7f5" />

It all depends on the degree of your precision needed for your question. If the above deviation is no worries then I would say go for it with the mirroring
