### ISSUE TITLE
installation issue: OSError: Unable to synchronously open file

### ISSUE THREAD

**Issue by Guanhaoyu104** [PolarBean/DeepSlice#61]
Dear Author,

I hope this message finds you well. I have followed the instrutions that you wrote in the READ ME page and encounted this issue:
OSError: Unable to synchronously open file (truncated file: eof = 10399232, sblock->base_addr = 0, stored_eof = 91884032)
This issue happened after I downloaded these documents from the website you set
![image](https://github.com/user-attachments/assets/21763e4f-3675-4065-8a0e-a26aaec6a17f)

I try to run my code and this issue occured
![image](https://github.com/user-attachments/assets/5cd75b93-feca-4a94-817c-4d8b1386b723)
I'd appreciated it if you can help me solve this problems and hope DeepSlice getting better and better.

**Comment by PolarBean** [comment]
HI! the files are the wrong size. this is how it looks on my machine 
![image](https://github.com/user-attachments/assets/0777cb9c-d6ff-4144-b681-bc6d232af6df)
to fix this try the following. 
1. Delete 'Allen_Mixed_Best.h5' and 'xception_weights_tf_dim_ordering_tf_kernels.h5'
2. Restart the kernel in PyCharm
3. Rerun the code and allow DeepSlice to fetch the new files. 

Please let me know if this solves your problem.

**Comment by PolarBean** [comment]
this is indicating that model.predict found no images (when running model.predict it should have returned such an error). make sure you are correctly specifying folderpath. 

it should look something like 
'C:/users/Guanhaoyu104/Documents/folderwithimages/'

**Comment by Guanhaoyu104** [comment]
thank you for your gentle help!

**Comment by PolarBean** [comment]
You're welcome 😊
