### ISSUE TITLE
Alignment Problems

### ISSUE THREAD

**Issue by TacticBlack** [PolarBean/DeepSlice#8]
Our lab is very excited about the prospects of much faster atlas registration. However, I've tried on the client-side and using the web platform to auto-align images but unfortunately the model performed quite poorly on my DAPI images. Even when providing section number information I get alignment like this (see images ) for all my images. Not one image aligned well. I am hoping there is a fix for this and that I am just doing something wrong. Please advise.

In addition, the QuickNII software may be buggy as well. The same image pops up or does not change when you change images, e.g. DeepSlice Alignment2.jpg and 3 should be two different images but the DAPI image remains the same when selecting another image from the series or just never shows up at all (DeepSlice Alignment4.jpg) despite restarting the application many times.

DeepSlice Alignment1
![DeepSlice Alignment1](https://user-images.githubusercontent.com/79601721/166486830-be3dbad7-9004-46c7-ae92-cae8ed96d7e1.JPG)
DeepSlice Alignment2
![DeepSlice Alignment2](https://user-images.githubusercontent.com/79601721/166486864-6235ef00-eba2-45f5-8625-9fe772617027.JPG)
DeepSlice Alignment3
![DeepSlice Alignment3](https://user-images.githubusercontent.com/79601721/166486874-3249af75-c414-4fa5-b386-47980c390bb3.JPG)
DeepSlice Alignment4
![DeepSlice Alignment4](https://user-images.githubusercontent.com/79601721/166486913-4b84c5be-6d37-44d5-a861-7111d3de1962.JPG)

**Comment by PolarBean** [comment]
interesting, I should write a trouble shooting guide which goes through common problems people face. Here are the likeliest problems. 
* Try turning off use section numbers to see if one section is throwing out the series.  
* DeepSlice requires 8-bit images, check the bit-depth and convert them in image-J if they're anything else. 
* Try turning off the slower more accurate option, this usually improves things but once in a blue moon the two models conflict though I've only seen this once

As for QuickNII it can be slower with non 8-bit images or high-resolutions. Due to your problems with DeepSlice and QuickNII I'd guess you have non 8-bit images. 

Let me know if anything suggested here helps!

**Comment by TacticBlack** [comment]
You suggestion helped considerably with alignment and I discovered a discrepancy between the online and client-side versions production of image file paths. 

### Alignment improvement
Converting to 8-bit tiffs worked to resolve a sizable portion of the alignment issue as did converting to JPG downsampled by 50%:
**Image1:**
![OnlineJPGAlignment](https://user-images.githubusercontent.com/79601721/166701747-07f5be61-9088-4193-b0d6-caa6cca1cda6.JPG)
**Image2**
![OnlineJPGAlignment2](https://user-images.githubusercontent.com/79601721/166703884-13d0ae86-0171-441a-974b-5640b6bfa0a8.JPG)
**Image3**
![OnlineJPGAlignment3](https://user-images.githubusercontent.com/79601721/166703905-9888eaf2-d023-4544-b7f4-1b0456445ce5.JPG)

This already saves a considerable chunk of time for me in my current workflow during the step where I manually find the AP coordinates for use with WholeBrain which is awesome! However, as you can see in the images, the alignment of smaller structures is problematic (e.g. anterior commissure, lateral ventricles). 

Aside from adjusting each one manually, what more can be done to ensure edge and internal structure alignment?

### File path discrepancy causing issues with QuickNII
As I was testing different things, I noticed that the client-side-generated .xml files were the ones that did not show the images in QuickNII. If you look at the file path in the top of the window of image 4 below and compare it to the same in image 1 you will see it too.

**Image4**
![ClientSideJPGAlignment4](https://user-images.githubusercontent.com/79601721/166705712-5859f886-de72-43b4-af9a-0136d99a1199.JPG)

The "ch1_DAPI" folder is listed twice in the path for the one generated on the client side. Consequently, the images dont get loaded into QuickNII for comparison to the atlas. I originally saved the output of the model to the parent folder ("Images") and tried saving it to the child folder with the images to no avail. The image file paths remained containing the duplicate folder. I can open a separate bug report for this if you'd like.

**Comment by PolarBean** [comment]
Im glad it works well for you! For your smaller structures you should save a json in QuickNII and use Visualign https://www.nitrc.org/projects/visualign/ to warp the section. However I have just realised that there is a problem with the DeepSlice output and VisuAlign compatibility. I'm working on this now and will comment here when solved. 

Please open a new issue for the filepath discrepancy problem :)

**Comment by PolarBean** [comment]
I've updated DeepSlice web so the output will now be compatible with VisuAlign!

I recommend you start with DeepSlice, make small adjustments with QuickNII change the size and position of the alignment as you see fit. Then use Visualign for all your smaller regions and warping of the section.

**Comment by PolarBean** [comment]
Thanks for using DeepSlice :)
